services:
  - type: web
    name: yt-scriptgen
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase-service-account.json
